<div style="
  position: fixed;
  bottom: 8px;
  right: 8px;
  font-size: 12px;
  color: rgba(255,255,255,0.6);
  font-weight: bold;
  pointer-events: none;
  z-index: 1000;
  text-align: right;
">
  Code from MrTT<br>
  Programming by E.B.
</div>

